name = "asay-global"
compatibility_date = "2024-09-25"

[compatibility_flags]
nodejs_compat = true

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[[env.production]]
name = "asay-global"

[[env.preview]]
name = "asay-global-preview"
