name: Deploy to Cloudflare Pages (OpenNext)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci --progress=false
        working-directory: ./asay-global

      - name: Build with OpenNext
        run: npx --yes @opennextjs/cloudflare@latest build
        working-directory: ./asay-global

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: pages deploy .open-next --project-name=${{ secrets.CF_PAGES_PROJECT }}
        working-directory: ./asay-global


